#!/usr/bin/env node
// Regenerate the courses seed migration from data/courses.json.
//   node scripts/gen_course_seed.mjs [out.sql]
// Upserts by id, so re-running after adding a course (scripts/fetch_course.py)
// is safe. Write new output to a NEW migration file once the first one is applied.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = process.argv[2] ?? join(root, "supabase/migrations/20261003000003_seed_courses.sql");
const { source, courses } = JSON.parse(readFileSync(join(root, "data/courses.json"), "utf8"));

const lit = (s) => (s == null ? "null" : `'${String(s).replaceAll("'", "''")}'`);
const arr = (a) => (a == null ? "null" : `array[${a.map(lit).join(", ")}]::text[]`);

const rows = courses.map((c) => {
  const json = JSON.stringify(c);
  if (json.includes("$course$")) throw new Error(`course ${c.id} contains the quote tag`);
  return `  (${lit(c.id)}, ${lit(c.name)}, ${lit(c.address)}, ${arr(c.nines)}, $course$${json}$course$::jsonb)`;
});

writeFileSync(
  out,
  `-- GENERATED by scripts/gen_course_seed.mjs from data/courses.json — do not edit by hand.
-- Course data: ${source}

insert into public.courses (id, name, address, nines, data) values
${rows.join(",\n")}
on conflict (id) do update
  set name = excluded.name, address = excluded.address, nines = excluded.nines,
      data = excluded.data, updated_at = now();
`,
);
console.log(`wrote ${courses.length} courses -> ${out}`);
