#!/usr/bin/env node
// Regenerate the courses seed migration from data/courses.json.
//   node scripts/gen_course_seed.mjs [out.sql]
//   node scripts/gen_course_seed.mjs out.sql --ids a,b,c          # only these courses
//   node scripts/gen_course_seed.mjs out.sql --exclude a,b         # every course except these
//   node scripts/gen_course_seed.mjs out_%d.sql --split 6000000    # chunks of <= ~6 MB each:
//        out_1.sql, out_2.sql, ... (%d is replaced by 1, 2, ...; or pass a list of names
//        with --names f1.sql,f2.sql). Each file is a self-contained upsert of its courses.
// Upserts by id, so re-running after adding a course (scripts/fetch_course.py,
// scripts/import_region.py) is safe. Write new output to a NEW migration file once the previous
// one is applied (the default path below is the original, already-applied seed).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const opt = (name) => {
  const i = args.indexOf(name);
  if (i < 0) return null;
  const v = args[i + 1];
  args.splice(i, 2);
  return v;
};
const ids = opt("--ids")?.split(",");
const exclude = new Set(opt("--exclude")?.split(",") ?? []);
const split = Number(opt("--split") ?? 0);
const names = opt("--names")?.split(",");
const out = args[0] ?? join(root, "supabase/migrations/20261003000003_seed_courses.sql");
const { source, courses: all } = JSON.parse(readFileSync(join(root, "data/courses.json"), "utf8"));

let courses = all.filter((c) => !exclude.has(c.id));
if (ids) {
  const missing = ids.filter((id) => !all.some((c) => c.id === id));
  if (missing.length) throw new Error(`unknown course ids: ${missing.join(", ")}`);
  courses = courses.filter((c) => ids.includes(c.id));
}

const lit = (s) => (s == null ? "null" : `'${String(s).replaceAll("'", "''")}'`);
const arr = (a) => (a == null ? "null" : `array[${a.map(lit).join(", ")}]::text[]`);

// `features` (scripts/fetch_features.py) goes in its own column so `data` stays small.
const quote = (id, v) => {
  if (v == null) return "null";
  const json = JSON.stringify(v);
  if (json.includes("$course$")) throw new Error(`course ${id} contains the quote tag`);
  return `$course$${json}$course$::jsonb`;
};
const row = ({ features, ...c }) =>
  `  (${lit(c.id)}, ${lit(c.name)}, ${lit(c.address)}, ${arr(c.nines)}, ${quote(c.id, c)}, ${quote(c.id, features)})`;

const sql = (rows, note = "") => `-- GENERATED by scripts/gen_course_seed.mjs from data/courses.json — do not edit by hand.
-- Course data: ${source}${note}

insert into public.courses (id, name, address, nines, data, features) values
${rows.join(",\n")}
on conflict (id) do update
  set name = excluded.name, address = excluded.address, nines = excluded.nines,
      data = excluded.data, features = excluded.features, updated_at = now();
`;

if (!split) {
  writeFileSync(out, sql(courses.map(row)));
  console.log(`wrote ${courses.length} courses -> ${out}`);
} else {
  // Greedy chunks in data order, each under `split` bytes.
  const chunks = [[]];
  let size = 0;
  for (const c of courses) {
    const r = row(c);
    const bytes = Buffer.byteLength(r) + 2;
    if (size + bytes > split - 1000 && chunks.at(-1).length) {
      chunks.push([]);
      size = 0;
    }
    chunks.at(-1).push(r);
    size += bytes;
  }
  if (names && names.length !== chunks.length)
    throw new Error(`--names has ${names.length} files but the data needs ${chunks.length}`);
  chunks.forEach((rows, i) => {
    const file = names ? names[i] : out.replace("%d", String(i + 1));
    if (file === out && chunks.length > 1) throw new Error("use %d in the output path (or --names) to split");
    writeFileSync(file, sql(rows, `\n-- Part ${i + 1} of ${chunks.length} (${rows.length} courses).`));
    console.log(`wrote ${rows.length} courses -> ${file}`);
  });
}
