#!/usr/bin/env node
// Regenerate the courses seed migration from data/courses.json.
//   node scripts/gen_course_seed.mjs [out.sql]
// Upserts by id, so re-running after adding a course (scripts/fetch_course.py)
// is safe. Write new output to a NEW migration file once the previous one is applied
// (the default path below is the original, already-applied seed).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = process.argv[2] ?? join(root, "supabase/migrations/20261003000003_seed_courses.sql");
const { source, courses } = JSON.parse(readFileSync(join(root, "data/courses.json"), "utf8"));

const lit = (s) => (s == null ? "null" : `'${String(s).replaceAll("'", "''")}'`);
const arr = (a) => (a == null ? "null" : `array[${a.map(lit).join(", ")}]::text[]`);

// `features` (scripts/fetch_features.py) goes in its own column so `data` stays small.
const quote = (id, v) => {
  if (v == null) return "null";
  const json = JSON.stringify(v);
  if (json.includes("$course$")) throw new Error(`course ${id} contains the quote tag`);
  return `$course$${json}$course$::jsonb`;
};
const rows = courses.map(({ features, ...c }) =>
  `  (${lit(c.id)}, ${lit(c.name)}, ${lit(c.address)}, ${arr(c.nines)}, ${quote(c.id, c)}, ${quote(c.id, features)})`);

writeFileSync(
  out,
  `-- GENERATED by scripts/gen_course_seed.mjs from data/courses.json — do not edit by hand.
-- Course data: ${source}

insert into public.courses (id, name, address, nines, data, features) values
${rows.join(",\n")}
on conflict (id) do update
  set name = excluded.name, address = excluded.address, nines = excluded.nines,
      data = excluded.data, features = excluded.features, updated_at = now();
`,
);
console.log(`wrote ${courses.length} courses -> ${out}`);
